
services:
             
  logstash:
    build:
      context: .
      dockerfile: dev/dockerfile  
    restart: unless-stopped         
    # image: taothong/logstash_autodel:1.0
    container_name: logstash    
    ports:
      - "5044:5044"
      - "5044:5044/udp"
    cap_add:
      - SYS_PTRACE
    volumes:
      - ./outputlogs:/var/log/logstash/outputlogs
      - ./logstash.conf:/etc/logstash/conf.d/logstash.conf
      - ./createdfile.log:/home/link/createdfile.log
      # - ./action.sh:/home/link/action.sh


#############################################################################

  kibana:
    image: kibana:8.13.4
    container_name: kibana  
    restart: unless-stopped       
    ports:
      - 80:5601
    depends_on:
      - elasticsearch 

  elasticsearch:
    image: rapidfort/elasticsearch:8.13.4
    restart: unless-stopped       
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
    ports:
      - "9200:9200"

