version: '3'
services:
             
  logstash6:
    build:
      context: .
      dockerfile: dev/Dockerfile  
    # image: taothong/logstash_autodel:1.0
    container_name: logstash6     
    ports:
      - "5044:5044"
      - "5044:5044/udp"
    cap_add:
      - SYS_PTRACE
    volumes:
      - ./outputlogs:/var/log/logstash/outputlogs
      - ./logstash.conf:/etc/logstash/conf.d/logstash.conf
      - ./createdfile.log:/home/link/createdfile.log
      # - ./action.sh:/home/link/action.sh


