version: '3'
services:

  client:
    image: taothong/logstash_autodel:1.0
    container_name: logstash_autodel  
    ports:
      - 5044:5044
    networks:
      - link        
    volumes:
      - ./createdfile.log:/home/link/createdfile.log
      - ./outputlogs:/var/log/logstash/outputlogs 
      - ./logstash.conf:/etc/logstash/conf.d/logstash.conf     
    
# ------------------------------------------------------------
  
networks:
  link:
    driver: bridge      